project_id = "coop-sys"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "https://coop-sys.vercel.app"
additional_redirect_urls = ["https://coop-sys.vercel.app", "http://127.0.0.1:5173", "http://localhost:5173"]
